const router=require('express').Router(),db=require('../database/db'),{authenticate}=require('../middleware/auth');
router.get('/',authenticate,async(req,res)=>{const{companyId}=req.query;const[r]=companyId?await db.query('SELECT si.*,sg.name as group_name FROM stock_items si LEFT JOIN stock_groups sg ON si.stock_group_id=sg.id WHERE si.company_id=? ORDER BY si.id',[companyId]):await db.query('SELECT * FROM stock_items ORDER BY id');res.json(r);});
router.post('/',authenticate,async(req,res)=>{const{companyId,name,stockGroupId,unit,openingQty,openingRate,gstRate,hsnCode,reorderLevel,description,barcode}=req.body;const oq=openingQty||0,or2=openingRate||0;const[r]=await db.query('INSERT INTO stock_items(company_id,name,stock_group_id,unit,opening_qty,opening_rate,opening_value,gst_rate,hsn_code,reorder_level,description,barcode)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[companyId,name,stockGroupId,unit,oq,or2,oq*or2,gstRate||0,hsnCode,reorderLevel||0,description,barcode]);const[rows]=await db.query('SELECT * FROM stock_items WHERE id=?',[r.insertId]);res.json(rows[0]);});
router.put('/:id',authenticate,async(req,res)=>{const{name,stockGroupId,unit,openingQty,openingRate,gstRate,hsnCode,reorderLevel,description,barcode}=req.body;await db.query('UPDATE stock_items SET name=?,stock_group_id=?,unit=?,opening_qty=?,opening_rate=?,opening_value=?,gst_rate=?,hsn_code=?,reorder_level=?,description=?,barcode=? WHERE id=?',[name,stockGroupId,unit,openingQty,openingRate,openingQty*openingRate,gstRate,hsnCode,reorderLevel,description,barcode,req.params.id]);const[r]=await db.query('SELECT * FROM stock_items WHERE id=?',[req.params.id]);res.json(r[0]);});
router.delete('/:id',authenticate,async(req,res)=>{await db.query('DELETE FROM stock_items WHERE id=?',[req.params.id]);res.json({message:'Deleted'});});
router.get('/reports/summary/:companyId',authenticate,async(req,res)=>{const[items]=await db.query('SELECT * FROM stock_items WHERE company_id=?',[req.params.companyId]);const result=await Promise.all(items.map(async item=>{const[[inD]]=await db.query("SELECT COALESCE(SUM(sve.qty),0) as qty,COALESCE(SUM(sve.amount),0) as val FROM stock_voucher_entries sve JOIN stock_vouchers sv ON sve.stock_voucher_id=sv.id WHERE sv.company_id=? AND sve.stock_item_id=? AND sv.voucher_type='Receipt'",[req.params.companyId,item.id]);const[[outD]]=await db.query("SELECT COALESCE(SUM(sve.qty),0) as qty,COALESCE(SUM(sve.amount),0) as val FROM stock_voucher_entries sve JOIN stock_vouchers sv ON sve.stock_voucher_id=sv.id WHERE sv.company_id=? AND sve.stock_item_id=? AND sv.voucher_type='Issue'",[req.params.companyId,item.id]);return{itemId:item.id,itemName:item.name,unit:item.unit,openingQty:+item.opening_qty,openingValue:+item.opening_value,inQty:+inD.qty,inValue:+inD.val,outQty:+outD.qty,outValue:+outD.val,closingQty:+item.opening_qty+(+inD.qty)-(+outD.qty),closingValue:+item.opening_value+(+inD.val)-(+outD.val),reorderLevel:+item.reorder_level};}));res.json(result);});
router.get('/reports/ledger/:companyId/:itemId',authenticate,async(req,res)=>{const[item]=await db.query('SELECT * FROM stock_items WHERE id=? AND company_id=?',[req.params.itemId,req.params.companyId]);if(!item.length)return res.status(404).json({error:'Not found'});const[vouchers]=await db.query('SELECT sv.*,sve.qty,sve.rate,sve.amount FROM stock_vouchers sv JOIN stock_voucher_entries sve ON sv.id=sve.stock_voucher_id WHERE sv.company_id=? AND sve.stock_item_id=? ORDER BY sv.date',[req.params.companyId,req.params.itemId]);let balance=+item[0].opening_qty;const entries=vouchers.map(v=>{const inQ=v.voucher_type==='Receipt'?+v.qty:0;const outQ=v.voucher_type==='Issue'?+v.qty:0;balance+=inQ-outQ;return{date:v.date,voucherType:v.voucher_type,narration:v.narration,inQty:inQ,outQty:outQ,rate:+v.rate,balance};});res.json({item:item[0],entries});});
router.get('/reports/movement/:companyId',authenticate,async(req,res)=>{const{fromDate,toDate}=req.query;let sql='SELECT si.name,si.unit,sv.voucher_type,SUM(sve.qty) as total_qty,SUM(sve.amount) as total_value FROM stock_voucher_entries sve JOIN stock_vouchers sv ON sve.stock_voucher_id=sv.id JOIN stock_items si ON sve.stock_item_id=si.id WHERE sv.company_id=?';const p=[req.params.companyId];if(fromDate){sql+=' AND sv.date>=?';p.push(fromDate);}if(toDate){sql+=' AND sv.date<=?';p.push(toDate);}sql+=' GROUP BY si.id,sv.voucher_type ORDER BY si.name';const[r]=await db.query(sql,p);res.json(r);});
module.exports=router;
