/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'id' : bigint,
  'name' : string,
  'financialYearEnd' : string,
  'gstin' : string,
  'currency' : string,
  'address' : string,
  'financialYearStart' : string,
}
export interface DayBookEntry {
  'voucherType' : string,
  'entries' : Array<VoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
}
export interface GSTR1Entry {
  'invoiceValue' : number,
  'cess' : number,
  'cgst' : number,
  'igst' : number,
  'taxableValue' : number,
  'sgst' : number,
  'hsnCode' : string,
  'invoiceDate' : Time,
  'invoiceNumber' : bigint,
  'partyName' : string,
  'placeOfSupply' : string,
  'partyGSTIN' : string,
}
export interface GSTR3BSummary {
  'outwardTaxableSGST' : number,
  'inwardSuppliesITC' : number,
  'exemptSupplies' : number,
  'inwardCGST' : number,
  'outwardTaxableSupplies' : number,
  'inwardIGST' : number,
  'netCGST' : number,
  'inwardSGST' : number,
  'netIGST' : number,
  'netSGST' : number,
  'totalTaxPayable' : number,
  'zeroRatedSupplies' : number,
  'outwardTaxableCGST' : number,
  'outwardTaxableIGST' : number,
}
export interface GSTSettings {
  'stateCode' : string,
  'stateName' : string,
  'registrationType' : string,
  'companyId' : bigint,
}
export interface GSTVoucher {
  'id' : bigint,
  'date' : Time,
  'isInterState' : boolean,
  'voucherType' : string,
  'entries' : Array<GSTVoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
  'partyName' : string,
  'placeOfSupply' : string,
  'partyGSTIN' : string,
  'companyId' : bigint,
}
export interface GSTVoucherEntry {
  'ledgerId' : bigint,
  'taxableAmount' : [] | [number],
  'entryType' : string,
  'igstRate' : [] | [number],
  'igstAmount' : [] | [number],
  'hsnCode' : [] | [string],
  'sgstRate' : [] | [number],
  'cgstAmount' : [] | [number],
  'sgstAmount' : [] | [number],
  'amount' : number,
  'cgstRate' : [] | [number],
  'cessAmount' : [] | [number],
}
export interface HSNCode {
  'id' : bigint,
  'code' : string,
  'description' : string,
  'gstRate' : number,
}
export interface Ledger {
  'id' : bigint,
  'name' : string,
  'groupId' : bigint,
  'balanceType' : string,
  'openingBalance' : number,
  'companyId' : bigint,
}
export interface LedgerGroup {
  'id' : bigint,
  'isPredefined' : boolean,
  'nature' : string,
  'parentGroup' : [] | [bigint],
  'name' : string,
}
export interface TaxLedgerBalance {
  'totalDebits' : number,
  'closingBalance' : number,
  'ledgerName' : string,
  'ledgerType' : string,
  'openingBalance' : number,
  'totalCredits' : number,
  'taxType' : string,
}
export type Time = bigint;
export interface TrialBalanceEntry {
  'creditTotal' : number,
  'debitTotal' : number,
  'ledgerName' : string,
}
export interface Voucher {
  'id' : bigint,
  'date' : Time,
  'voucherType' : string,
  'entries' : Array<VoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
  'companyId' : bigint,
}
export interface VoucherEntry {
  'ledgerId' : bigint,
  'entryType' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addLedgerGroup' : ActorMethod<[string, [] | [bigint], string], LedgerGroup>,
  'createCompany' : ActorMethod<
    [string, string, string, string, string, string],
    Company
  >,
  'createGSTVoucher' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      Time,
      string,
      Array<GSTVoucherEntry>,
      string,
      string,
      string,
      boolean,
    ],
    { 'voucher' : GSTVoucher, 'voucherId' : bigint }
  >,
  'createHSNCode' : ActorMethod<[string, string, number], HSNCode>,
  'createLedger' : ActorMethod<
    [bigint, string, bigint, number, string],
    Ledger
  >,
  'createVoucher' : ActorMethod<
    [bigint, string, bigint, Time, string, Array<VoucherEntry>],
    { 'voucher' : Voucher, 'voucherId' : bigint }
  >,
  'getAllCompanies' : ActorMethod<[], Array<Company>>,
  'getAllGSTVouchers' : ActorMethod<[bigint], Array<GSTVoucher>>,
  'getAllHSNCodes' : ActorMethod<[], Array<HSNCode>>,
  'getAllLedgerGroups' : ActorMethod<[], Array<LedgerGroup>>,
  'getAllLedgers' : ActorMethod<[], Array<Ledger>>,
  'getDayBook' : ActorMethod<[bigint, Time], Array<DayBookEntry>>,
  'getGSTR1' : ActorMethod<[bigint, Time, Time], Array<GSTR1Entry>>,
  'getGSTR3B' : ActorMethod<[bigint, Time, Time], GSTR3BSummary>,
  'getGSTSettings' : ActorMethod<[bigint], [] | [GSTSettings]>,
  'getTaxLedgerBalances' : ActorMethod<[bigint], Array<TaxLedgerBalance>>,
  'getTrialBalance' : ActorMethod<[bigint], Array<TrialBalanceEntry>>,
  'initializePredefinedLedgerGroups' : ActorMethod<[], undefined>,
  'setGSTSettings' : ActorMethod<[bigint, string, string, string], GSTSettings>,
  'updateHSNCode' : ActorMethod<[bigint, string, string, number], HSNCode>,
  'updateLedger' : ActorMethod<
    [bigint, string, bigint, number, string],
    Ledger
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];