/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LedgerGroup = IDL.Record({
  'id' : IDL.Nat,
  'isPredefined' : IDL.Bool,
  'nature' : IDL.Text,
  'parentGroup' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
});
export const Company = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'financialYearEnd' : IDL.Text,
  'gstin' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'financialYearStart' : IDL.Text,
});
export const Time = IDL.Int;
export const GSTVoucherEntry = IDL.Record({
  'ledgerId' : IDL.Nat,
  'taxableAmount' : IDL.Opt(IDL.Float64),
  'entryType' : IDL.Text,
  'igstRate' : IDL.Opt(IDL.Float64),
  'igstAmount' : IDL.Opt(IDL.Float64),
  'hsnCode' : IDL.Opt(IDL.Text),
  'sgstRate' : IDL.Opt(IDL.Float64),
  'cgstAmount' : IDL.Opt(IDL.Float64),
  'sgstAmount' : IDL.Opt(IDL.Float64),
  'amount' : IDL.Float64,
  'cgstRate' : IDL.Opt(IDL.Float64),
  'cessAmount' : IDL.Opt(IDL.Float64),
});
export const GSTVoucher = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'isInterState' : IDL.Bool,
  'voucherType' : IDL.Text,
  'entries' : IDL.Vec(GSTVoucherEntry),
  'voucherNumber' : IDL.Nat,
  'narration' : IDL.Text,
  'partyName' : IDL.Text,
  'placeOfSupply' : IDL.Text,
  'partyGSTIN' : IDL.Text,
  'companyId' : IDL.Nat,
});
export const HSNCode = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'gstRate' : IDL.Float64,
});
export const Ledger = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'groupId' : IDL.Nat,
  'balanceType' : IDL.Text,
  'openingBalance' : IDL.Float64,
  'companyId' : IDL.Nat,
});
export const VoucherEntry = IDL.Record({
  'ledgerId' : IDL.Nat,
  'entryType' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Voucher = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'voucherType' : IDL.Text,
  'entries' : IDL.Vec(VoucherEntry),
  'voucherNumber' : IDL.Nat,
  'narration' : IDL.Text,
  'companyId' : IDL.Nat,
});
export const DayBookEntry = IDL.Record({
  'voucherType' : IDL.Text,
  'entries' : IDL.Vec(VoucherEntry),
  'voucherNumber' : IDL.Nat,
  'narration' : IDL.Text,
});
export const GSTR1Entry = IDL.Record({
  'invoiceValue' : IDL.Float64,
  'cess' : IDL.Float64,
  'cgst' : IDL.Float64,
  'igst' : IDL.Float64,
  'taxableValue' : IDL.Float64,
  'sgst' : IDL.Float64,
  'hsnCode' : IDL.Text,
  'invoiceDate' : Time,
  'invoiceNumber' : IDL.Nat,
  'partyName' : IDL.Text,
  'placeOfSupply' : IDL.Text,
  'partyGSTIN' : IDL.Text,
});
export const GSTR3BSummary = IDL.Record({
  'outwardTaxableSGST' : IDL.Float64,
  'inwardSuppliesITC' : IDL.Float64,
  'exemptSupplies' : IDL.Float64,
  'inwardCGST' : IDL.Float64,
  'outwardTaxableSupplies' : IDL.Float64,
  'inwardIGST' : IDL.Float64,
  'netCGST' : IDL.Float64,
  'inwardSGST' : IDL.Float64,
  'netIGST' : IDL.Float64,
  'netSGST' : IDL.Float64,
  'totalTaxPayable' : IDL.Float64,
  'zeroRatedSupplies' : IDL.Float64,
  'outwardTaxableCGST' : IDL.Float64,
  'outwardTaxableIGST' : IDL.Float64,
});
export const GSTSettings = IDL.Record({
  'stateCode' : IDL.Text,
  'stateName' : IDL.Text,
  'registrationType' : IDL.Text,
  'companyId' : IDL.Nat,
});
export const TaxLedgerBalance = IDL.Record({
  'totalDebits' : IDL.Float64,
  'closingBalance' : IDL.Float64,
  'ledgerName' : IDL.Text,
  'ledgerType' : IDL.Text,
  'openingBalance' : IDL.Float64,
  'totalCredits' : IDL.Float64,
  'taxType' : IDL.Text,
});
export const TrialBalanceEntry = IDL.Record({
  'creditTotal' : IDL.Float64,
  'debitTotal' : IDL.Float64,
  'ledgerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLedgerGroup' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [LedgerGroup],
      [],
    ),
  'createCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Company],
      [],
    ),
  'createGSTVoucher' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Vec(GSTVoucherEntry),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Record({ 'voucher' : GSTVoucher, 'voucherId' : IDL.Nat })],
      [],
    ),
  'createHSNCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [HSNCode], []),
  'createLedger' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [Ledger],
      [],
    ),
  'createVoucher' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, Time, IDL.Text, IDL.Vec(VoucherEntry)],
      [IDL.Record({ 'voucher' : Voucher, 'voucherId' : IDL.Nat })],
      [],
    ),
  'getAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getAllGSTVouchers' : IDL.Func([IDL.Nat], [IDL.Vec(GSTVoucher)], ['query']),
  'getAllHSNCodes' : IDL.Func([], [IDL.Vec(HSNCode)], ['query']),
  'getAllLedgerGroups' : IDL.Func([], [IDL.Vec(LedgerGroup)], ['query']),
  'getAllLedgers' : IDL.Func([], [IDL.Vec(Ledger)], ['query']),
  'getDayBook' : IDL.Func([IDL.Nat, Time], [IDL.Vec(DayBookEntry)], ['query']),
  'getGSTR1' : IDL.Func(
      [IDL.Nat, Time, Time],
      [IDL.Vec(GSTR1Entry)],
      ['query'],
    ),
  'getGSTR3B' : IDL.Func([IDL.Nat, Time, Time], [GSTR3BSummary], ['query']),
  'getGSTSettings' : IDL.Func([IDL.Nat], [IDL.Opt(GSTSettings)], ['query']),
  'getTaxLedgerBalances' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TaxLedgerBalance)],
      ['query'],
    ),
  'getTrialBalance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TrialBalanceEntry)],
      ['query'],
    ),
  'initializePredefinedLedgerGroups' : IDL.Func([], [], []),
  'setGSTSettings' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [GSTSettings],
      [],
    ),
  'updateHSNCode' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [HSNCode],
      [],
    ),
  'updateLedger' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [Ledger],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LedgerGroup = IDL.Record({
    'id' : IDL.Nat,
    'isPredefined' : IDL.Bool,
    'nature' : IDL.Text,
    'parentGroup' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
  });
  const Company = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'financialYearEnd' : IDL.Text,
    'gstin' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'financialYearStart' : IDL.Text,
  });
  const Time = IDL.Int;
  const GSTVoucherEntry = IDL.Record({
    'ledgerId' : IDL.Nat,
    'taxableAmount' : IDL.Opt(IDL.Float64),
    'entryType' : IDL.Text,
    'igstRate' : IDL.Opt(IDL.Float64),
    'igstAmount' : IDL.Opt(IDL.Float64),
    'hsnCode' : IDL.Opt(IDL.Text),
    'sgstRate' : IDL.Opt(IDL.Float64),
    'cgstAmount' : IDL.Opt(IDL.Float64),
    'sgstAmount' : IDL.Opt(IDL.Float64),
    'amount' : IDL.Float64,
    'cgstRate' : IDL.Opt(IDL.Float64),
    'cessAmount' : IDL.Opt(IDL.Float64),
  });
  const GSTVoucher = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'isInterState' : IDL.Bool,
    'voucherType' : IDL.Text,
    'entries' : IDL.Vec(GSTVoucherEntry),
    'voucherNumber' : IDL.Nat,
    'narration' : IDL.Text,
    'partyName' : IDL.Text,
    'placeOfSupply' : IDL.Text,
    'partyGSTIN' : IDL.Text,
    'companyId' : IDL.Nat,
  });
  const HSNCode = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'gstRate' : IDL.Float64,
  });
  const Ledger = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'groupId' : IDL.Nat,
    'balanceType' : IDL.Text,
    'openingBalance' : IDL.Float64,
    'companyId' : IDL.Nat,
  });
  const VoucherEntry = IDL.Record({
    'ledgerId' : IDL.Nat,
    'entryType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Voucher = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'voucherType' : IDL.Text,
    'entries' : IDL.Vec(VoucherEntry),
    'voucherNumber' : IDL.Nat,
    'narration' : IDL.Text,
    'companyId' : IDL.Nat,
  });
  const DayBookEntry = IDL.Record({
    'voucherType' : IDL.Text,
    'entries' : IDL.Vec(VoucherEntry),
    'voucherNumber' : IDL.Nat,
    'narration' : IDL.Text,
  });
  const GSTR1Entry = IDL.Record({
    'invoiceValue' : IDL.Float64,
    'cess' : IDL.Float64,
    'cgst' : IDL.Float64,
    'igst' : IDL.Float64,
    'taxableValue' : IDL.Float64,
    'sgst' : IDL.Float64,
    'hsnCode' : IDL.Text,
    'invoiceDate' : Time,
    'invoiceNumber' : IDL.Nat,
    'partyName' : IDL.Text,
    'placeOfSupply' : IDL.Text,
    'partyGSTIN' : IDL.Text,
  });
  const GSTR3BSummary = IDL.Record({
    'outwardTaxableSGST' : IDL.Float64,
    'inwardSuppliesITC' : IDL.Float64,
    'exemptSupplies' : IDL.Float64,
    'inwardCGST' : IDL.Float64,
    'outwardTaxableSupplies' : IDL.Float64,
    'inwardIGST' : IDL.Float64,
    'netCGST' : IDL.Float64,
    'inwardSGST' : IDL.Float64,
    'netIGST' : IDL.Float64,
    'netSGST' : IDL.Float64,
    'totalTaxPayable' : IDL.Float64,
    'zeroRatedSupplies' : IDL.Float64,
    'outwardTaxableCGST' : IDL.Float64,
    'outwardTaxableIGST' : IDL.Float64,
  });
  const GSTSettings = IDL.Record({
    'stateCode' : IDL.Text,
    'stateName' : IDL.Text,
    'registrationType' : IDL.Text,
    'companyId' : IDL.Nat,
  });
  const TaxLedgerBalance = IDL.Record({
    'totalDebits' : IDL.Float64,
    'closingBalance' : IDL.Float64,
    'ledgerName' : IDL.Text,
    'ledgerType' : IDL.Text,
    'openingBalance' : IDL.Float64,
    'totalCredits' : IDL.Float64,
    'taxType' : IDL.Text,
  });
  const TrialBalanceEntry = IDL.Record({
    'creditTotal' : IDL.Float64,
    'debitTotal' : IDL.Float64,
    'ledgerName' : IDL.Text,
  });
  
  return IDL.Service({
    'addLedgerGroup' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [LedgerGroup],
        [],
      ),
    'createCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Company],
        [],
      ),
    'createGSTVoucher' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Vec(GSTVoucherEntry),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Record({ 'voucher' : GSTVoucher, 'voucherId' : IDL.Nat })],
        [],
      ),
    'createHSNCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [HSNCode],
        [],
      ),
    'createLedger' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [Ledger],
        [],
      ),
    'createVoucher' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, Time, IDL.Text, IDL.Vec(VoucherEntry)],
        [IDL.Record({ 'voucher' : Voucher, 'voucherId' : IDL.Nat })],
        [],
      ),
    'getAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getAllGSTVouchers' : IDL.Func([IDL.Nat], [IDL.Vec(GSTVoucher)], ['query']),
    'getAllHSNCodes' : IDL.Func([], [IDL.Vec(HSNCode)], ['query']),
    'getAllLedgerGroups' : IDL.Func([], [IDL.Vec(LedgerGroup)], ['query']),
    'getAllLedgers' : IDL.Func([], [IDL.Vec(Ledger)], ['query']),
    'getDayBook' : IDL.Func(
        [IDL.Nat, Time],
        [IDL.Vec(DayBookEntry)],
        ['query'],
      ),
    'getGSTR1' : IDL.Func(
        [IDL.Nat, Time, Time],
        [IDL.Vec(GSTR1Entry)],
        ['query'],
      ),
    'getGSTR3B' : IDL.Func([IDL.Nat, Time, Time], [GSTR3BSummary], ['query']),
    'getGSTSettings' : IDL.Func([IDL.Nat], [IDL.Opt(GSTSettings)], ['query']),
    'getTaxLedgerBalances' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TaxLedgerBalance)],
        ['query'],
      ),
    'getTrialBalance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TrialBalanceEntry)],
        ['query'],
      ),
    'initializePredefinedLedgerGroups' : IDL.Func([], [], []),
    'setGSTSettings' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [GSTSettings],
        [],
      ),
    'updateHSNCode' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [HSNCode],
        [],
      ),
    'updateLedger' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [Ledger],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };