/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccount {
  'id' : bigint,
  'linkedLedgerId' : bigint,
  'ifscCode' : string,
  'isActive' : boolean,
  'bankName' : string,
  'accountName' : string,
  'openingBalance' : number,
  'accountNumber' : string,
  'branchName' : string,
  'companyId' : bigint,
}
export interface BankTransaction {
  'id' : bigint,
  'isReconciled' : boolean,
  'transactionType' : string,
  'bankAccountId' : bigint,
  'date' : Time,
  'description' : string,
  'voucherId' : [] | [bigint],
  'amount' : number,
  'reconciledDate' : [] | [Time],
  'companyId' : bigint,
}
export interface ChequeEntry {
  'id' : bigint,
  'status' : string,
  'chequeDate' : Time,
  'chequeType' : string,
  'chequeNumber' : string,
  'bankAccountId' : bigint,
  'payeeName' : string,
  'voucherId' : [] | [bigint],
  'amount' : number,
  'remarks' : string,
  'companyId' : bigint,
}
export interface Company {
  'id' : bigint,
  'name' : string,
  'financialYearEnd' : string,
  'gstin' : string,
  'currency' : string,
  'address' : string,
  'financialYearStart' : string,
}
export interface DayBookEntry {
  'voucherType' : string,
  'entries' : Array<VoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
}
export interface Employee {
  'id' : bigint,
  'pan' : string,
  'pfApplicable' : boolean,
  'employeeCode' : string,
  'bankAccount' : string,
  'name' : string,
  'designation' : string,
  'isActive' : boolean,
  'bankName' : string,
  'dateOfJoining' : string,
  'department' : string,
  'esiApplicable' : boolean,
  'companyId' : bigint,
}
export interface GSTR1Entry {
  'invoiceValue' : number,
  'cess' : number,
  'cgst' : number,
  'igst' : number,
  'taxableValue' : number,
  'sgst' : number,
  'hsnCode' : string,
  'invoiceDate' : Time,
  'invoiceNumber' : bigint,
  'partyName' : string,
  'placeOfSupply' : string,
  'partyGSTIN' : string,
}
export interface GSTR3BSummary {
  'outwardTaxableSGST' : number,
  'inwardSuppliesITC' : number,
  'exemptSupplies' : number,
  'inwardCGST' : number,
  'outwardTaxableSupplies' : number,
  'inwardIGST' : number,
  'netCGST' : number,
  'inwardSGST' : number,
  'netIGST' : number,
  'netSGST' : number,
  'totalTaxPayable' : number,
  'zeroRatedSupplies' : number,
  'outwardTaxableCGST' : number,
  'outwardTaxableIGST' : number,
}
export interface GSTSettings {
  'stateCode' : string,
  'stateName' : string,
  'registrationType' : string,
  'companyId' : bigint,
}
export interface GSTVoucher {
  'id' : bigint,
  'date' : Time,
  'isInterState' : boolean,
  'voucherType' : string,
  'entries' : Array<GSTVoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
  'partyName' : string,
  'placeOfSupply' : string,
  'partyGSTIN' : string,
  'companyId' : bigint,
}
export interface GSTVoucherEntry {
  'ledgerId' : bigint,
  'taxableAmount' : [] | [number],
  'entryType' : string,
  'igstRate' : [] | [number],
  'igstAmount' : [] | [number],
  'hsnCode' : [] | [string],
  'sgstRate' : [] | [number],
  'cgstAmount' : [] | [number],
  'sgstAmount' : [] | [number],
  'amount' : number,
  'cgstRate' : [] | [number],
  'cessAmount' : [] | [number],
}
export interface HSNCode {
  'id' : bigint,
  'code' : string,
  'description' : string,
  'gstRate' : number,
}
export interface Ledger {
  'id' : bigint,
  'name' : string,
  'groupId' : bigint,
  'balanceType' : string,
  'openingBalance' : number,
  'companyId' : bigint,
}
export interface LedgerGroup {
  'id' : bigint,
  'isPredefined' : boolean,
  'nature' : string,
  'parentGroup' : [] | [bigint],
  'name' : string,
}
export interface PayrollEntry {
  'da' : number,
  'pf' : number,
  'esi' : number,
  'hra' : number,
  'tds' : number,
  'totalDeductions' : number,
  'employeeName' : string,
  'otherAllowances' : number,
  'designation' : string,
  'netPayable' : number,
  'employeeId' : bigint,
  'basic' : number,
  'grossEarnings' : number,
  'specialAllowance' : number,
  'otherDeductions' : number,
  'department' : string,
  'conveyance' : number,
  'professionalTax' : number,
}
export interface PayrollVoucher {
  'id' : bigint,
  'month' : bigint,
  'year' : bigint,
  'processedAt' : Time,
  'entries' : Array<PayrollEntry>,
  'companyId' : bigint,
}
export interface SalaryStructure {
  'da' : number,
  'id' : bigint,
  'pf' : number,
  'esi' : number,
  'hra' : number,
  'tds' : number,
  'otherAllowances' : number,
  'employeeId' : bigint,
  'basic' : number,
  'specialAllowance' : number,
  'otherDeductions' : number,
  'conveyance' : number,
  'professionalTax' : number,
  'companyId' : bigint,
}
export interface StockGroup {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'parentGroupId' : [] | [bigint],
}
export interface StockItem {
  'id' : bigint,
  'stockGroupId' : bigint,
  'name' : string,
  'unit' : string,
  'openingRate' : number,
  'hsnCode' : string,
  'openingValue' : number,
  'openingQty' : number,
  'gstRate' : number,
  'companyId' : bigint,
}
export interface StockLedgerEntry {
  'outQty' : number,
  'balance' : number,
  'date' : Time,
  'voucherType' : string,
  'voucherNumber' : bigint,
  'narration' : string,
  'inQty' : number,
  'inValue' : number,
  'outValue' : number,
}
export interface StockSummaryEntry {
  'itemId' : bigint,
  'outQty' : number,
  'closingValue' : number,
  'unit' : string,
  'closingQty' : number,
  'itemName' : string,
  'openingValue' : number,
  'openingQty' : number,
  'inQty' : number,
  'inValue' : number,
  'outValue' : number,
}
export interface StockVoucher {
  'id' : bigint,
  'date' : Time,
  'voucherType' : string,
  'entries' : Array<StockVoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
  'companyId' : bigint,
}
export interface StockVoucherEntry {
  'qty' : number,
  'warehouseTo' : [] | [string],
  'stockItemId' : bigint,
  'rate' : number,
  'warehouseFrom' : [] | [string],
  'amount' : number,
}
export interface TaxLedgerBalance {
  'totalDebits' : number,
  'closingBalance' : number,
  'ledgerName' : string,
  'ledgerType' : string,
  'openingBalance' : number,
  'totalCredits' : number,
  'taxType' : string,
}
export type Time = bigint;
export interface TrialBalanceEntry {
  'creditTotal' : number,
  'debitTotal' : number,
  'ledgerName' : string,
}
export interface Voucher {
  'id' : bigint,
  'date' : Time,
  'voucherType' : string,
  'entries' : Array<VoucherEntry>,
  'voucherNumber' : bigint,
  'narration' : string,
  'companyId' : bigint,
}
export interface VoucherEntry {
  'ledgerId' : bigint,
  'entryType' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addLedgerGroup' : ActorMethod<[string, [] | [bigint], string], LedgerGroup>,
  'createBankAccount' : ActorMethod<
    [bigint, string, string, string, string, string, bigint, number],
    BankAccount
  >,
  'createBankTransaction' : ActorMethod<
    [bigint, bigint, Time, string, number, string, [] | [bigint]],
    BankTransaction
  >,
  'createChequeEntry' : ActorMethod<
    [bigint, bigint, string, Time, number, string, string, string],
    ChequeEntry
  >,
  'createCompany' : ActorMethod<
    [string, string, string, string, string, string],
    Company
  >,
  'createEmployee' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
    ],
    Employee
  >,
  'createGSTVoucher' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      Time,
      string,
      Array<GSTVoucherEntry>,
      string,
      string,
      string,
      boolean,
    ],
    { 'voucher' : GSTVoucher, 'voucherId' : bigint }
  >,
  'createHSNCode' : ActorMethod<[string, string, number], HSNCode>,
  'createLedger' : ActorMethod<
    [bigint, string, bigint, number, string],
    Ledger
  >,
  'createPayrollVoucher' : ActorMethod<
    [bigint, bigint, bigint, Array<PayrollEntry>],
    PayrollVoucher
  >,
  'createStockGroup' : ActorMethod<[string, [] | [bigint], string], StockGroup>,
  'createStockItem' : ActorMethod<
    [bigint, string, bigint, string, number, number, number, string],
    StockItem
  >,
  'createStockVoucher' : ActorMethod<
    [bigint, string, bigint, Time, string, Array<StockVoucherEntry>],
    { 'voucher' : StockVoucher, 'voucherId' : bigint }
  >,
  'createVoucher' : ActorMethod<
    [bigint, string, bigint, Time, string, Array<VoucherEntry>],
    { 'voucher' : Voucher, 'voucherId' : bigint }
  >,
  'getAllBankAccounts' : ActorMethod<[bigint], Array<BankAccount>>,
  'getAllCheques' : ActorMethod<[bigint], Array<ChequeEntry>>,
  'getAllCompanies' : ActorMethod<[], Array<Company>>,
  'getAllEmployees' : ActorMethod<[bigint], Array<Employee>>,
  'getAllGSTVouchers' : ActorMethod<[bigint], Array<GSTVoucher>>,
  'getAllHSNCodes' : ActorMethod<[], Array<HSNCode>>,
  'getAllLedgerGroups' : ActorMethod<[], Array<LedgerGroup>>,
  'getAllLedgers' : ActorMethod<[], Array<Ledger>>,
  'getAllPayrollVouchers' : ActorMethod<[bigint], Array<PayrollVoucher>>,
  'getAllSalaryStructures' : ActorMethod<[bigint], Array<SalaryStructure>>,
  'getAllStockGroups' : ActorMethod<[], Array<StockGroup>>,
  'getAllStockItems' : ActorMethod<[], Array<StockItem>>,
  'getAllStockVouchers' : ActorMethod<[bigint], Array<StockVoucher>>,
  'getBankBalance' : ActorMethod<[bigint, bigint], number>,
  'getBankStatement' : ActorMethod<
    [bigint, bigint, Time, Time],
    Array<BankTransaction>
  >,
  'getBankTransactions' : ActorMethod<[bigint, bigint], Array<BankTransaction>>,
  'getChequesByBankAccount' : ActorMethod<[bigint, bigint], Array<ChequeEntry>>,
  'getDayBook' : ActorMethod<[bigint, Time], Array<DayBookEntry>>,
  'getGSTR1' : ActorMethod<[bigint, Time, Time], Array<GSTR1Entry>>,
  'getGSTR3B' : ActorMethod<[bigint, Time, Time], GSTR3BSummary>,
  'getGSTSettings' : ActorMethod<[bigint], [] | [GSTSettings]>,
  'getPayrollVoucher' : ActorMethod<
    [bigint, bigint, bigint],
    [] | [PayrollVoucher]
  >,
  'getSalaryStructure' : ActorMethod<[bigint, bigint], [] | [SalaryStructure]>,
  'getStockLedger' : ActorMethod<[bigint, bigint], Array<StockLedgerEntry>>,
  'getStockSummary' : ActorMethod<[bigint], Array<StockSummaryEntry>>,
  'getTaxLedgerBalances' : ActorMethod<[bigint], Array<TaxLedgerBalance>>,
  'getTrialBalance' : ActorMethod<[bigint], Array<TrialBalanceEntry>>,
  'getUnreconciledTransactions' : ActorMethod<
    [bigint, bigint],
    Array<BankTransaction>
  >,
  'initializePredefinedLedgerGroups' : ActorMethod<[], undefined>,
  'reconcileTransaction' : ActorMethod<
    [bigint, [] | [bigint], string],
    BankTransaction
  >,
  'saveSalaryStructure' : ActorMethod<
    [
      bigint,
      bigint,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    SalaryStructure
  >,
  'setGSTSettings' : ActorMethod<[bigint, string, string, string], GSTSettings>,
  'unreconcileTransaction' : ActorMethod<[bigint], BankTransaction>,
  'updateBankAccount' : ActorMethod<
    [bigint, string, string, string, string, string, bigint, number, boolean],
    BankAccount
  >,
  'updateChequeStatus' : ActorMethod<[bigint, string, string], ChequeEntry>,
  'updateEmployee' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      boolean,
    ],
    Employee
  >,
  'updateHSNCode' : ActorMethod<[bigint, string, string, number], HSNCode>,
  'updateLedger' : ActorMethod<
    [bigint, string, bigint, number, string],
    Ledger
  >,
  'updateStockItem' : ActorMethod<
    [bigint, string, bigint, string, number, number, number, string],
    StockItem
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];