const BASE_URL = (import.meta as any).env?.VITE_API_URL || 'http://localhost:3001/api';
function getToken() { return localStorage.getItem('hk_jwt_token'); }
async function req<T>(method: string, path: string, body?: unknown): Promise<T> {
  const h: Record<string,string> = { 'Content-Type': 'application/json' };
  const t = getToken(); if (t) h['Authorization'] = `Bearer ${t}`;
  const r = await fetch(`${BASE_URL}${path}`, { method, headers: h, body: body ? JSON.stringify(body) : undefined });
  if (!r.ok) { const e = await r.json().catch(() => ({ message: r.statusText })); throw new Error(e.message || `API ${r.status}`); }
  return r.json();
}
export const api = {
  login: (u: string, p: string) => req<any>('POST', '/auth/login', { username: u, password: p }),
  getProfile: () => req<any>('GET', '/auth/profile'),
  updateProfile: (d: any) => req<any>('PUT', '/auth/profile', d),
  getUsers: () => req<any[]>('GET', '/users'),
  createUser: (d: any) => req<any>('POST', '/users', d),
  updateUser: (id: number, d: any) => req<any>('PUT', `/users/${id}`, d),
  deleteUser: (id: number) => req<any>('DELETE', `/users/${id}`),
  resetUserPassword: (id: number, p: string) => req<any>('POST', `/users/${id}/reset-password`, { newPassword: p }),
  getCompanies: () => req<any[]>('GET', '/companies'),
  createCompany: (d: any) => req<any>('POST', '/companies', d),
  updateCompany: (id: number, d: any) => req<any>('PUT', `/companies/${id}`, d),
  deleteCompany: (id: number) => req<any>('DELETE', `/companies/${id}`),
  getLedgerGroups: () => req<any[]>('GET', '/ledger-groups'),
  createLedgerGroup: (d: any) => req<any>('POST', '/ledger-groups', d),
  updateLedgerGroup: (id: number, d: any) => req<any>('PUT', `/ledger-groups/${id}`, d),
  deleteLedgerGroup: (id: number) => req<any>('DELETE', `/ledger-groups/${id}`),
  getLedgers: (cid?: number) => req<any[]>('GET', cid ? `/ledgers?companyId=${cid}` : '/ledgers'),
  createLedger: (d: any) => req<any>('POST', '/ledgers', d),
  updateLedger: (id: number, d: any) => req<any>('PUT', `/ledgers/${id}`, d),
  deleteLedger: (id: number) => req<any>('DELETE', `/ledgers/${id}`),
  getTrialBalance: (cid: number) => req<any>('GET', `/ledgers/trial-balance/${cid}`),
  getVouchers: (cid: number, type?: string) => req<any[]>('GET', `/vouchers?companyId=${cid}${type?`&type=${type}`:''}`),
  getVoucher: (id: number) => req<any>('GET', `/vouchers/${id}`),
  createVoucher: (d: any) => req<any>('POST', '/vouchers', d),
  updateVoucher: (id: number, d: any) => req<any>('PUT', `/vouchers/${id}`, d),
  deleteVoucher: (id: number) => req<any>('DELETE', `/vouchers/${id}`),
  getDayBook: (cid: number, date?: string) => req<any[]>('GET', `/vouchers/day-book/${cid}${date?`?date=${date}`:''}`),
  getGSTSettings: (cid: number) => req<any>('GET', `/gst/settings/${cid}`),
  saveGSTSettings: (cid: number, d: any) => req<any>('PUT', `/gst/settings/${cid}`, d),
  getGSTVouchers: (cid: number) => req<any[]>('GET', `/gst/vouchers/${cid}`),
  createGSTVoucher: (d: any) => req<any>('POST', '/gst/vouchers', d),
  getGSTR1: (cid: number, m: string, y: string) => req<any>('GET', `/gst/gstr1/${cid}?month=${m}&year=${y}`),
  getGSTR3B: (cid: number, m: string, y: string) => req<any>('GET', `/gst/gstr3b/${cid}?month=${m}&year=${y}`),
  getHSNCodes: () => req<any[]>('GET', '/hsn-codes'),
  createHSNCode: (d: any) => req<any>('POST', '/hsn-codes', d),
  updateHSNCode: (id: number, d: any) => req<any>('PUT', `/hsn-codes/${id}`, d),
  getStockGroups: () => req<any[]>('GET', '/stock-groups'),
  createStockGroup: (d: any) => req<any>('POST', '/stock-groups', d),
  getStockItems: (cid?: number) => req<any[]>('GET', cid ? `/stock-items?companyId=${cid}` : '/stock-items'),
  createStockItem: (d: any) => req<any>('POST', '/stock-items', d),
  updateStockItem: (id: number, d: any) => req<any>('PUT', `/stock-items/${id}`, d),
  getStockSummary: (cid: number) => req<any[]>('GET', `/stock-items/summary/${cid}`),
  getStockLedger: (cid: number, iid: number) => req<any[]>('GET', `/stock-vouchers/ledger/${cid}/${iid}`),
  getPayrollVouchers: (cid: number) => req<any[]>('GET', `/payroll/vouchers/${cid}`),
  getPayrollVoucher: (id: number) => req<any>('GET', `/payroll/vouchers/detail/${id}`),
  createPayrollVoucher: (d: any) => req<any>('POST', '/payroll/vouchers', d),
  getSalaryStructures: (cid: number) => req<any[]>('GET', `/payroll/salary-structures/${cid}`),
  getSalaryStructure: (cid: number, eid: number) => req<any>('GET', `/payroll/salary-structures/${cid}/${eid}`),
  saveSalaryStructure: (d: any) => req<any>('POST', '/payroll/salary-structures', d),
  getEmployees: (cid: number) => req<any[]>('GET', `/employees/${cid}`),
  createEmployee: (d: any) => req<any>('POST', '/employees', d),
  updateEmployee: (id: number, d: any) => req<any>('PUT', `/employees/${id}`, d),
  getBankAccounts: (cid: number) => req<any[]>('GET', `/banking/accounts/${cid}`),
  createBankAccount: (d: any) => req<any>('POST', '/banking/accounts', d),
  updateBankAccount: (id: number, d: any) => req<any>('PUT', `/banking/accounts/${id}`, d),
  getBankTransactions: (aid: number) => req<any[]>('GET', `/banking/transactions/${aid}`),
  getBRS: (aid: number) => req<any>('GET', `/banking/brs/${aid}`),
  getCheques: (aid: number) => req<any[]>('GET', `/cheques/${aid}`),
  createCheque: (d: any) => req<any>('POST', '/cheques', d),
  updateChequeStatus: (id: number, s: string) => req<any>('PUT', `/cheques/${id}/status`, { status: s }),
  getFixedAssets: (cid: number) => req<any[]>('GET', `/fixed-assets/${cid}`),
  createFixedAsset: (d: any) => req<any>('POST', '/fixed-assets', d),
  updateFixedAsset: (id: number, d: any) => req<any>('PUT', `/fixed-assets/${id}`, d),
  deleteFixedAsset: (id: number) => req<any>('DELETE', `/fixed-assets/${id}`),
  getCostCentres: (cid: number) => req<any[]>('GET', `/cost-centres/${cid}`),
  createCostCentre: (d: any) => req<any>('POST', '/cost-centres', d),
  getCurrencies: () => req<any[]>('GET', '/currencies'),
  createCurrency: (d: any) => req<any>('POST', '/currencies', d),
  getBalanceSheet: (cid: number) => req<any>('GET', `/reports/balance-sheet/${cid}`),
  getPL: (cid: number) => req<any>('GET', `/reports/profit-loss/${cid}`),
  getCashFlow: (cid: number) => req<any>('GET', `/reports/cash-flow/${cid}`),
  getBudgets: (cid: number) => req<any[]>('GET', `/budgets/${cid}`),
  createBudget: (d: any) => req<any>('POST', '/budgets', d),
  getBudgetVsActual: (cid: number) => req<any>('GET', `/budgets/vs-actual/${cid}`),
  getCustomers: (cid: number) => req<any[]>('GET', `/customers/${cid}`),
  createCustomer: (d: any) => req<any>('POST', '/customers', d),
  updateCustomer: (id: number, d: any) => req<any>('PUT', `/customers/${id}`, d),
  getVendors: (cid: number) => req<any[]>('GET', `/vendors/${cid}`),
  createVendor: (d: any) => req<any>('POST', '/vendors', d),
  updateVendor: (id: number, d: any) => req<any>('PUT', `/vendors/${id}`, d),
  getPurchaseOrders: (cid: number) => req<any[]>('GET', `/orders/purchase/${cid}`),
  createPurchaseOrder: (d: any) => req<any>('POST', '/orders/purchase', d),
  getSalesOrders: (cid: number) => req<any[]>('GET', `/orders/sales/${cid}`),
  createSalesOrder: (d: any) => req<any>('POST', '/orders/sales', d),
  getLeads: (cid: number) => req<any[]>('GET', `/crm/leads/${cid}`),
  createLead: (d: any) => req<any>('POST', '/crm/leads', d),
  updateLead: (id: number, d: any) => req<any>('PUT', `/crm/leads/${id}`, d),
  convertLead: (id: number) => req<any>('POST', `/crm/leads/${id}/convert`),
  getPOSSessions: (cid: number) => req<any[]>('GET', `/pos/sessions/${cid}`),
  openPOSSession: (d: any) => req<any>('POST', '/pos/sessions', d),
  createPOSSale: (d: any) => req<any>('POST', '/pos/sales', d),
  getBranches: (cid: number) => req<any[]>('GET', `/branches/${cid}`),
  createBranch: (d: any) => req<any>('POST', '/branches', d),
  getServiceOrders: (cid: number) => req<any[]>('GET', `/service/orders/${cid}`),
  createServiceOrder: (d: any) => req<any>('POST', '/service/orders', d),
  getServiceTickets: (cid: number) => req<any[]>('GET', `/service/tickets/${cid}`),
  createServiceTicket: (d: any) => req<any>('POST', '/service/tickets', d),
  getSubscriptions: (cid: number) => req<any[]>('GET', `/subscriptions/${cid}`),
  createSubscription: (d: any) => req<any>('POST', '/subscriptions', d),
  getEWayBills: (cid: number) => req<any[]>('GET', `/compliance/eway-bills/${cid}`),
  getEInvoices: (cid: number) => req<any[]>('GET', `/compliance/einvoices/${cid}`),
  getGSTFilingHistory: (cid: number) => req<any[]>('GET', `/compliance/gst-filings/${cid}`),
  getProjects: (cid: number) => req<any[]>('GET', `/projects/${cid}`),
  createProject: (d: any) => req<any>('POST', '/projects', d),
  getConsolidatedBS: () => req<any>('GET', '/multi-company/balance-sheet'),
  getConsolidatedPL: () => req<any>('GET', '/multi-company/profit-loss'),
  getAnalyticsKPIs: (cid: number) => req<any>('GET', `/analytics/kpis/${cid}`),
  getCashFlowForecast: (cid: number, days: number) => req<any>('GET', `/analytics/cash-flow-forecast/${cid}?days=${days}`),
  getNotifications: () => req<any[]>('GET', '/notifications'),
  markNotificationRead: (id: number) => req<any>('PUT', `/notifications/${id}/read`),
  getSmartAlerts: (cid: number) => req<any[]>('GET', `/notifications/alerts/${cid}`),
  getRules: (cid: number) => req<any[]>('GET', `/rules/${cid}`),
  createRule: (d: any) => req<any>('POST', '/rules', d),
  getEventLedger: (cid: number) => req<any[]>('GET', `/event-ledger/${cid}`),
  undoEvent: (id: number) => req<any>('POST', `/event-ledger/${id}/undo`),
  getMakerCheckerPending: () => req<any[]>('GET', '/maker-checker/pending'),
  approveMakerChecker: (id: number, r: string) => req<any>('POST', `/maker-checker/${id}/approve`, { remarks: r }),
  rejectMakerChecker: (id: number, r: string) => req<any>('POST', `/maker-checker/${id}/reject`, { remarks: r }),
  getVoucherComments: (vid: number) => req<any[]>('GET', `/collaboration/comments/${vid}`),
  addVoucherComment: (d: any) => req<any>('POST', '/collaboration/comments', d),
  getVoucherTasks: (vid: number) => req<any[]>('GET', `/collaboration/tasks/${vid}`),
  createVoucherTask: (d: any) => req<any>('POST', '/collaboration/tasks', d),
  getEcomOrders: (cid: number) => req<any[]>('GET', `/ecommerce/orders/${cid}`),
  convertEcomOrder: (id: number) => req<any>('POST', `/ecommerce/orders/${id}/convert`),
  sendWhatsApp: (d: any) => req<any>('POST', '/whatsapp/send', d),
  getWhatsAppQueue: (cid: number) => req<any[]>('GET', `/whatsapp/queue/${cid}`),
  getCustomFields: (e: string) => req<any[]>('GET', `/customization/fields/${e}`),
  getWorkflows: (cid: number) => req<any[]>('GET', `/customization/workflows/${cid}`),
  getTallyImports: (cid: number) => req<any[]>('GET', `/tally-import/${cid}`),
  startTallyImport: (d: any) => req<any>('POST', '/tally-import', d),
  saveAIConfig: (d: any) => req<any>('PUT', '/ai-tools/config', d),
  detectAnomalies: (cid: number) => req<any>('POST', `/ai-tools/anomalies/${cid}`),
  getAppSettings: () => req<any>('GET', '/settings'),
  saveAppSettings: (d: any) => req<any>('PUT', '/settings', d),
  getPremiumFeatures: () => req<any[]>('GET', '/settings/premium-features'),
  savePremiumFeatures: (d: any) => req<any>('PUT', '/settings/premium-features', d),
  submitContactQuery: (d: any) => req<any>('POST', '/settings/contact-queries', d),
  exportAllData: (cid: number) => req<any>('GET', `/data/export/${cid}`),
  getAuditLog: (cid: number) => req<any[]>('GET', `/audit-log/${cid}`),
  testRemoteDB: (c: any) => req<any>('POST', '/utilities/test-db', c),
};
export function setAuthToken(t: string) { localStorage.setItem('hk_jwt_token', t); }
export function clearAuthToken() { localStorage.removeItem('hk_jwt_token'); }
