/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VoucherEntry {
    ledgerId: bigint;
    entryType: string;
    amount: number;
}
export type Time = bigint;
export interface GSTVoucherEntry {
    ledgerId: bigint;
    taxableAmount?: number;
    entryType: string;
    igstRate?: number;
    igstAmount?: number;
    hsnCode?: string;
    sgstRate?: number;
    cgstAmount?: number;
    sgstAmount?: number;
    amount: number;
    cgstRate?: number;
    cessAmount?: number;
}
export interface Company {
    id: bigint;
    name: string;
    financialYearEnd: string;
    gstin: string;
    currency: string;
    address: string;
    financialYearStart: string;
}
export interface TrialBalanceEntry {
    creditTotal: number;
    debitTotal: number;
    ledgerName: string;
}
export interface Voucher {
    id: bigint;
    date: Time;
    voucherType: string;
    entries: Array<VoucherEntry>;
    voucherNumber: bigint;
    narration: string;
    companyId: bigint;
}
export interface LedgerGroup {
    id: bigint;
    isPredefined: boolean;
    nature: string;
    parentGroup?: bigint;
    name: string;
}
export interface GSTSettings {
    stateCode: string;
    stateName: string;
    registrationType: string;
    companyId: bigint;
}
export interface HSNCode {
    id: bigint;
    code: string;
    description: string;
    gstRate: number;
}
export interface GSTVoucher {
    id: bigint;
    date: Time;
    isInterState: boolean;
    voucherType: string;
    entries: Array<GSTVoucherEntry>;
    voucherNumber: bigint;
    narration: string;
    partyName: string;
    placeOfSupply: string;
    partyGSTIN: string;
    companyId: bigint;
}
export interface GSTR3BSummary {
    outwardTaxableSGST: number;
    inwardSuppliesITC: number;
    exemptSupplies: number;
    inwardCGST: number;
    outwardTaxableSupplies: number;
    inwardIGST: number;
    netCGST: number;
    inwardSGST: number;
    netIGST: number;
    netSGST: number;
    totalTaxPayable: number;
    zeroRatedSupplies: number;
    outwardTaxableCGST: number;
    outwardTaxableIGST: number;
}
export interface TaxLedgerBalance {
    totalDebits: number;
    closingBalance: number;
    ledgerName: string;
    ledgerType: string;
    openingBalance: number;
    totalCredits: number;
    taxType: string;
}
export interface GSTR1Entry {
    invoiceValue: number;
    cess: number;
    cgst: number;
    igst: number;
    taxableValue: number;
    sgst: number;
    hsnCode: string;
    invoiceDate: Time;
    invoiceNumber: bigint;
    partyName: string;
    placeOfSupply: string;
    partyGSTIN: string;
}
export interface DayBookEntry {
    voucherType: string;
    entries: Array<VoucherEntry>;
    voucherNumber: bigint;
    narration: string;
}
export interface Ledger {
    id: bigint;
    name: string;
    groupId: bigint;
    balanceType: string;
    openingBalance: number;
    companyId: bigint;
}
export interface backendInterface {
    addLedgerGroup(name: string, parentGroup: bigint | null, nature: string): Promise<LedgerGroup>;
    createCompany(name: string, financialYearStart: string, financialYearEnd: string, currency: string, gstin: string, address: string): Promise<Company>;
    createGSTVoucher(companyId: bigint, voucherType: string, voucherNumber: bigint, date: Time, narration: string, entries: Array<GSTVoucherEntry>, partyName: string, partyGSTIN: string, placeOfSupply: string, isInterState: boolean): Promise<{
        voucher: GSTVoucher;
        voucherId: bigint;
    }>;
    createHSNCode(code: string, description: string, gstRate: number): Promise<HSNCode>;
    createLedger(companyId: bigint, name: string, groupId: bigint, openingBalance: number, balanceType: string): Promise<Ledger>;
    createVoucher(companyId: bigint, voucherType: string, voucherNumber: bigint, date: Time, narration: string, entries: Array<VoucherEntry>): Promise<{
        voucher: Voucher;
        voucherId: bigint;
    }>;
    getAllCompanies(): Promise<Array<Company>>;
    getAllGSTVouchers(companyId: bigint): Promise<Array<GSTVoucher>>;
    getAllHSNCodes(): Promise<Array<HSNCode>>;
    getAllLedgerGroups(): Promise<Array<LedgerGroup>>;
    getAllLedgers(): Promise<Array<Ledger>>;
    getDayBook(companyId: bigint, date: Time): Promise<Array<DayBookEntry>>;
    getGSTR1(companyId: bigint, fromDate: Time, toDate: Time): Promise<Array<GSTR1Entry>>;
    getGSTR3B(companyId: bigint, fromDate: Time, toDate: Time): Promise<GSTR3BSummary>;
    getGSTSettings(companyId: bigint): Promise<GSTSettings | null>;
    getTaxLedgerBalances(companyId: bigint): Promise<Array<TaxLedgerBalance>>;
    getTrialBalance(companyId: bigint): Promise<Array<TrialBalanceEntry>>;
    initializePredefinedLedgerGroups(): Promise<void>;
    setGSTSettings(companyId: bigint, registrationType: string, stateCode: string, stateName: string): Promise<GSTSettings>;
    updateHSNCode(id: bigint, code: string, description: string, gstRate: number): Promise<HSNCode>;
    updateLedger(ledgerId: bigint, name: string, groupId: bigint, openingBalance: number, balanceType: string): Promise<Ledger>;
}
import type { GSTSettings as _GSTSettings, GSTVoucher as _GSTVoucher, GSTVoucherEntry as _GSTVoucherEntry, LedgerGroup as _LedgerGroup, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLedgerGroup(arg0: string, arg1: bigint | null, arg2: string): Promise<LedgerGroup> {
        if (this.processError) {
            try {
                const result = await this.actor.addLedgerGroup(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_LedgerGroup_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLedgerGroup(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_LedgerGroup_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCompany(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompany(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompany(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createGSTVoucher(arg0: bigint, arg1: string, arg2: bigint, arg3: Time, arg4: string, arg5: Array<GSTVoucherEntry>, arg6: string, arg7: string, arg8: string, arg9: boolean): Promise<{
        voucher: GSTVoucher;
        voucherId: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createGSTVoucher(arg0, arg1, arg2, arg3, arg4, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGSTVoucher(arg0, arg1, arg2, arg3, arg4, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHSNCode(arg0: string, arg1: string, arg2: number): Promise<HSNCode> {
        if (this.processError) {
            try {
                const result = await this.actor.createHSNCode(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHSNCode(arg0, arg1, arg2);
            return result;
        }
    }
    async createLedger(arg0: bigint, arg1: string, arg2: bigint, arg3: number, arg4: string): Promise<Ledger> {
        if (this.processError) {
            try {
                const result = await this.actor.createLedger(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLedger(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createVoucher(arg0: bigint, arg1: string, arg2: bigint, arg3: Time, arg4: string, arg5: Array<VoucherEntry>): Promise<{
        voucher: Voucher;
        voucherId: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoucher(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoucher(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getAllCompanies(): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompanies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompanies();
            return result;
        }
    }
    async getAllGSTVouchers(arg0: bigint): Promise<Array<GSTVoucher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGSTVouchers(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGSTVouchers(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHSNCodes(): Promise<Array<HSNCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHSNCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHSNCodes();
            return result;
        }
    }
    async getAllLedgerGroups(): Promise<Array<LedgerGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLedgerGroups();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLedgerGroups();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLedgers(): Promise<Array<Ledger>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLedgers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLedgers();
            return result;
        }
    }
    async getDayBook(arg0: bigint, arg1: Time): Promise<Array<DayBookEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayBook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayBook(arg0, arg1);
            return result;
        }
    }
    async getGSTR1(arg0: bigint, arg1: Time, arg2: Time): Promise<Array<GSTR1Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGSTR1(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGSTR1(arg0, arg1, arg2);
            return result;
        }
    }
    async getGSTR3B(arg0: bigint, arg1: Time, arg2: Time): Promise<GSTR3BSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getGSTR3B(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGSTR3B(arg0, arg1, arg2);
            return result;
        }
    }
    async getGSTSettings(arg0: bigint): Promise<GSTSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGSTSettings(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGSTSettings(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaxLedgerBalances(arg0: bigint): Promise<Array<TaxLedgerBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxLedgerBalances(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxLedgerBalances(arg0);
            return result;
        }
    }
    async getTrialBalance(arg0: bigint): Promise<Array<TrialBalanceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrialBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrialBalance(arg0);
            return result;
        }
    }
    async initializePredefinedLedgerGroups(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePredefinedLedgerGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePredefinedLedgerGroups();
            return result;
        }
    }
    async setGSTSettings(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<GSTSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.setGSTSettings(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGSTSettings(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHSNCode(arg0: bigint, arg1: string, arg2: string, arg3: number): Promise<HSNCode> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHSNCode(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHSNCode(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLedger(arg0: bigint, arg1: string, arg2: bigint, arg3: number, arg4: string): Promise<Ledger> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLedger(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLedger(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_GSTVoucherEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GSTVoucherEntry): GSTVoucherEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_GSTVoucher_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GSTVoucher): GSTVoucher {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_LedgerGroup_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LedgerGroup): LedgerGroup {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GSTSettings]): GSTSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    isInterState: boolean;
    voucherType: string;
    entries: Array<_GSTVoucherEntry>;
    voucherNumber: bigint;
    narration: string;
    partyName: string;
    placeOfSupply: string;
    partyGSTIN: string;
    companyId: bigint;
}): {
    id: bigint;
    date: Time;
    isInterState: boolean;
    voucherType: string;
    entries: Array<GSTVoucherEntry>;
    voucherNumber: bigint;
    narration: string;
    partyName: string;
    placeOfSupply: string;
    partyGSTIN: string;
    companyId: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        isInterState: value.isInterState,
        voucherType: value.voucherType,
        entries: from_candid_vec_n11(_uploadFile, _downloadFile, value.entries),
        voucherNumber: value.voucherNumber,
        narration: value.narration,
        partyName: value.partyName,
        placeOfSupply: value.placeOfSupply,
        partyGSTIN: value.partyGSTIN,
        companyId: value.companyId
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ledgerId: bigint;
    taxableAmount: [] | [number];
    entryType: string;
    igstRate: [] | [number];
    igstAmount: [] | [number];
    hsnCode: [] | [string];
    sgstRate: [] | [number];
    cgstAmount: [] | [number];
    sgstAmount: [] | [number];
    amount: number;
    cgstRate: [] | [number];
    cessAmount: [] | [number];
}): {
    ledgerId: bigint;
    taxableAmount?: number;
    entryType: string;
    igstRate?: number;
    igstAmount?: number;
    hsnCode?: string;
    sgstRate?: number;
    cgstAmount?: number;
    sgstAmount?: number;
    amount: number;
    cgstRate?: number;
    cessAmount?: number;
} {
    return {
        ledgerId: value.ledgerId,
        taxableAmount: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.taxableAmount)),
        entryType: value.entryType,
        igstRate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.igstRate)),
        igstAmount: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.igstAmount)),
        hsnCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.hsnCode)),
        sgstRate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.sgstRate)),
        cgstAmount: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cgstAmount)),
        sgstAmount: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.sgstAmount)),
        amount: value.amount,
        cgstRate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cgstRate)),
        cessAmount: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cessAmount))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isPredefined: boolean;
    nature: string;
    parentGroup: [] | [bigint];
    name: string;
}): {
    id: bigint;
    isPredefined: boolean;
    nature: string;
    parentGroup?: bigint;
    name: string;
} {
    return {
        id: value.id,
        isPredefined: value.isPredefined,
        nature: value.nature,
        parentGroup: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.parentGroup)),
        name: value.name
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voucher: _GSTVoucher;
    voucherId: bigint;
}): {
    voucher: GSTVoucher;
    voucherId: bigint;
} {
    return {
        voucher: from_candid_GSTVoucher_n9(_uploadFile, _downloadFile, value.voucher),
        voucherId: value.voucherId
    };
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GSTVoucherEntry>): Array<GSTVoucherEntry> {
    return value.map((x)=>from_candid_GSTVoucherEntry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GSTVoucher>): Array<GSTVoucher> {
    return value.map((x)=>from_candid_GSTVoucher_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LedgerGroup>): Array<LedgerGroup> {
    return value.map((x)=>from_candid_LedgerGroup_n2(_uploadFile, _downloadFile, x));
}
function to_candid_GSTVoucherEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GSTVoucherEntry): _GSTVoucherEntry {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ledgerId: bigint;
    taxableAmount?: number;
    entryType: string;
    igstRate?: number;
    igstAmount?: number;
    hsnCode?: string;
    sgstRate?: number;
    cgstAmount?: number;
    sgstAmount?: number;
    amount: number;
    cgstRate?: number;
    cessAmount?: number;
}): {
    ledgerId: bigint;
    taxableAmount: [] | [number];
    entryType: string;
    igstRate: [] | [number];
    igstAmount: [] | [number];
    hsnCode: [] | [string];
    sgstRate: [] | [number];
    cgstAmount: [] | [number];
    sgstAmount: [] | [number];
    amount: number;
    cgstRate: [] | [number];
    cessAmount: [] | [number];
} {
    return {
        ledgerId: value.ledgerId,
        taxableAmount: value.taxableAmount ? candid_some(value.taxableAmount) : candid_none(),
        entryType: value.entryType,
        igstRate: value.igstRate ? candid_some(value.igstRate) : candid_none(),
        igstAmount: value.igstAmount ? candid_some(value.igstAmount) : candid_none(),
        hsnCode: value.hsnCode ? candid_some(value.hsnCode) : candid_none(),
        sgstRate: value.sgstRate ? candid_some(value.sgstRate) : candid_none(),
        cgstAmount: value.cgstAmount ? candid_some(value.cgstAmount) : candid_none(),
        sgstAmount: value.sgstAmount ? candid_some(value.sgstAmount) : candid_none(),
        amount: value.amount,
        cgstRate: value.cgstRate ? candid_some(value.cgstRate) : candid_none(),
        cessAmount: value.cessAmount ? candid_some(value.cessAmount) : candid_none()
    };
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GSTVoucherEntry>): Array<_GSTVoucherEntry> {
    return value.map((x)=>to_candid_GSTVoucherEntry_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
